repositories:
  - name: spark-operator
    url: https://kubeflow.github.io/spark-operator

releases:
  - name: spark-operator
    namespace: spark-operator
    createNamespace: true
    chart: spark-operator/spark-operator
    version: v2.2.0 
    values:
      - rbac:
          create: true
      - serviceAccounts:
          spark:
            create: true
  