apiVersion: apps/v1
kind: Deployment
metadata:
  name: kafka-consumer
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kafka-consumer
  template:
    metadata:
      labels:
        app: kafka-consumer
    spec:
      containers:
        - name: consumer
          image: seyiolufon/py-spark:latest
          command: ["python", "-u", "/opt/spark-app/app/kafka_consumer.py"]
          env:
            - name: KAFKA_BOOTSTRAP
              value: "kafka-service:9092"
          resources:
            requests:
              memory: "256Mi"
              cpu: "250m"
            limits:
              memory: "512Mi"
              cpu: "500m"