apiVersion: sparkoperator.k8s.io/v1beta2
kind: SparkApplication
metadata:
  name: spark-batch-job
  namespace: default
spec:
  type: Python
  mode: cluster
  image: seyiolufon/py-spark:latest
  imagePullPolicy: Always
  mainApplicationFile: local:///opt/spark-app/app/spark_batch.py
  sparkVersion: "3.5.5"
  restartPolicy:
    type: Never
  driver:
    cores: 1
    serviceAccount: spark-operator-spark
    env:
      - name: KAFKA_BOOTSTRAP
        value: "kafka-service:9092"
      - name: INPUT_TOPIC
        value: "input-events"
      - name: OUTPUT_TOPIC
        value: "output-events"
  executor:
    cores: 1
    instances: 2
    memory: 512m
    env:
      - name: KAFKA_BOOTSTRAP
        value: "kafka-service:9092"
      - name: INPUT_TOPIC
        value: "input-events"
      - name: OUTPUT_TOPIC
        value: "output-events"
  sparkConf:
    "spark.jars.packages": "org.apache.spark:spark-sql-kafka-0-10_2.12:3.5.5,org.apache.spark:spark-token-provider-kafka-0-10_2.12:3.5.5"
    "spark.jars.ivy": "/tmp/.ivy2"